version 0.2

phases:
  install:
    commands:
      #Install dependencies neede for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli